// Code generated by protoc-gen-go.
// source: pkg/swim/swimpb/swim.proto
// DO NOT EDIT!

/*
Package swimpb is a generated protocol buffer package.

It is generated from these files:
	pkg/swim/swimpb/swim.proto

It has these top-level messages:
	Member
	PingMessage
	Ack
*/
package swimpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_ALIVE   Status = 0
	Status_SUSPECT Status = 1
	Status_FAULTY  Status = 2
)

var Status_name = map[int32]string{
	0: "ALIVE",
	1: "SUSPECT",
	2: "FAULTY",
}
var Status_value = map[string]int32{
	"ALIVE":   0,
	"SUSPECT": 1,
	"FAULTY":  2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Type int32

const (
	Type_PING        Type = 0
	Type_PINGREQUEST Type = 1
	Type_BROADCAST   Type = 2
)

var Type_name = map[int32]string{
	0: "PING",
	1: "PINGREQUEST",
	2: "BROADCAST",
}
var Type_value = map[string]int32{
	"PING":        0,
	"PINGREQUEST": 1,
	"BROADCAST":   2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Member struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Addr        string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	Port        string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Status      Status `protobuf:"varint,4,opt,name=status,enum=github.com.chanyoung.nil.pkg.swimpb.Status" json:"status,omitempty"`
	Incarnation uint32 `protobuf:"varint,5,opt,name=incarnation" json:"incarnation,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Member) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Member) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Member) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Member) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ALIVE
}

func (m *Member) GetIncarnation() uint32 {
	if m != nil {
		return m.Incarnation
	}
	return 0
}

type PingMessage struct {
	Type    Type      `protobuf:"varint,1,opt,name=type,enum=github.com.chanyoung.nil.pkg.swimpb.Type" json:"type,omitempty"`
	Memlist []*Member `protobuf:"bytes,2,rep,name=memlist" json:"memlist,omitempty"`
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingMessage) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_PING
}

func (m *PingMessage) GetMemlist() []*Member {
	if m != nil {
		return m.Memlist
	}
	return nil
}

type Ack struct {
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Member)(nil), "github.com.chanyoung.nil.pkg.swimpb.Member")
	proto.RegisterType((*PingMessage)(nil), "github.com.chanyoung.nil.pkg.swimpb.PingMessage")
	proto.RegisterType((*Ack)(nil), "github.com.chanyoung.nil.pkg.swimpb.Ack")
	proto.RegisterEnum("github.com.chanyoung.nil.pkg.swimpb.Status", Status_name, Status_value)
	proto.RegisterEnum("github.com.chanyoung.nil.pkg.swimpb.Type", Type_name, Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Swim service

type SwimClient interface {
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*Ack, error)
}

type swimClient struct {
	cc *grpc.ClientConn
}

func NewSwimClient(cc *grpc.ClientConn) SwimClient {
	return &swimClient{cc}
}

func (c *swimClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/github.com.chanyoung.nil.pkg.swimpb.Swim/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Swim service

type SwimServer interface {
	Ping(context.Context, *PingMessage) (*Ack, error)
}

func RegisterSwimServer(s *grpc.Server, srv SwimServer) {
	s.RegisterService(&_Swim_serviceDesc, srv)
}

func _Swim_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwimServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.chanyoung.nil.pkg.swimpb.Swim/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwimServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Swim_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.chanyoung.nil.pkg.swimpb.Swim",
	HandlerType: (*SwimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Swim_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/swim/swimpb/swim.proto",
}

func init() { proto.RegisterFile("pkg/swim/swimpb/swim.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6e, 0xaa, 0x40,
	0x18, 0xc5, 0x05, 0x11, 0xf5, 0x23, 0x7a, 0xc9, 0xac, 0x88, 0x2b, 0xc2, 0xdd, 0x70, 0xbd, 0xcd,
	0xd4, 0xd8, 0x75, 0x17, 0x68, 0x69, 0x63, 0xa2, 0xad, 0x05, 0x6c, 0xd2, 0xee, 0xf8, 0x17, 0x9c,
	0x20, 0x7f, 0x02, 0x43, 0x8c, 0xcf, 0xd1, 0xc7, 0xe8, 0x4b, 0x36, 0x33, 0xb4, 0x89, 0x4b, 0x36,
	0x70, 0xe6, 0xe4, 0xfb, 0xe5, 0x3b, 0x73, 0x32, 0x30, 0x2b, 0xd3, 0xe4, 0xb6, 0x3e, 0x93, 0x8c,
	0x7f, 0xca, 0x80, 0xff, 0x70, 0x59, 0x15, 0xb4, 0x40, 0x7f, 0x13, 0x42, 0x8f, 0x4d, 0x80, 0xc3,
	0x22, 0xc3, 0xe1, 0xd1, 0xcf, 0x2f, 0x45, 0x93, 0x27, 0x38, 0x27, 0x27, 0x5c, 0xa6, 0x09, 0x6e,
	0xe7, 0x8d, 0x2f, 0x01, 0xe4, 0x5d, 0x9c, 0x05, 0x71, 0x85, 0x10, 0x48, 0x4d, 0x43, 0x22, 0x4d,
	0xd0, 0x05, 0x73, 0xec, 0x70, 0xcd, 0x3c, 0x3f, 0x8a, 0x2a, 0x4d, 0x6c, 0x3d, 0xa6, 0x99, 0x57,
	0x16, 0x15, 0xd5, 0xfa, 0xad, 0xc7, 0x34, 0x5a, 0x83, 0x5c, 0x53, 0x9f, 0x36, 0xb5, 0x26, 0xe9,
	0x82, 0x39, 0x5d, 0xfe, 0xc7, 0x1d, 0x96, 0x63, 0x97, 0x23, 0xce, 0x0f, 0x8a, 0x74, 0x50, 0x48,
	0x1e, 0xfa, 0x55, 0xee, 0x53, 0x52, 0xe4, 0xda, 0x40, 0x17, 0xcc, 0x89, 0x73, 0x6d, 0x19, 0x9f,
	0x02, 0x28, 0x7b, 0x92, 0x27, 0xbb, 0xb8, 0xae, 0xfd, 0x24, 0x46, 0xf7, 0x20, 0xd1, 0x4b, 0x19,
	0xf3, 0xc8, 0xd3, 0xe5, 0xbf, 0x4e, 0x4b, 0xbd, 0x4b, 0x19, 0x3b, 0x1c, 0x43, 0x36, 0x0c, 0xb3,
	0x38, 0x3b, 0x91, 0x9a, 0x6a, 0xa2, 0xde, 0x37, 0x95, 0x8e, 0xb1, 0xdb, 0xbe, 0x9c, 0x5f, 0xd6,
	0x18, 0x40, 0xdf, 0x0a, 0xd3, 0xf9, 0x0d, 0xc8, 0xed, 0x85, 0xd0, 0x18, 0x06, 0xd6, 0x76, 0xf3,
	0x66, 0xab, 0x3d, 0xa4, 0xc0, 0xd0, 0x3d, 0xb8, 0x7b, 0x7b, 0xed, 0xa9, 0x02, 0x02, 0x90, 0x1f,
	0xad, 0xc3, 0xd6, 0x7b, 0x57, 0xc5, 0xf9, 0x02, 0x24, 0x96, 0x04, 0x8d, 0x40, 0xda, 0x6f, 0x9e,
	0x9f, 0xd4, 0x1e, 0xfa, 0x03, 0x0a, 0x53, 0x8e, 0xfd, 0x7a, 0xb0, 0x5d, 0x36, 0x3e, 0x81, 0xf1,
	0xca, 0x79, 0xb1, 0x1e, 0xd6, 0x96, 0xeb, 0xa9, 0xe2, 0xf2, 0x04, 0x92, 0x7b, 0x26, 0x19, 0x8a,
	0x40, 0x62, 0x1d, 0xa0, 0x45, 0xa7, 0xb0, 0x57, 0x75, 0xcd, 0xcc, 0x4e, 0x84, 0x15, 0xa6, 0x46,
	0x6f, 0x35, 0xfa, 0x90, 0xdb, 0x73, 0x20, 0xf3, 0xe7, 0x74, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x24, 0x83, 0x58, 0xef, 0x6c, 0x02, 0x00, 0x00,
}
