// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/mds/mdspb/mds.proto

/*
Package mdspb is a generated protocol buffer package.

It is generated from these files:
	pkg/mds/mdspb/mds.proto

It has these top-level messages:
	GetClusterMapRequest
	GetClusterMapResponse
	AddUserRequest
	AddUserResponse
*/
package mdspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import github_com_chanyoung_nil_pkg_swimpb "github.com/chanyoung/nil/pkg/swim/swimpb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetClusterMapRequest struct {
}

func (m *GetClusterMapRequest) Reset()                    { *m = GetClusterMapRequest{} }
func (m *GetClusterMapRequest) String() string            { return proto.CompactTextString(m) }
func (*GetClusterMapRequest) ProtoMessage()               {}
func (*GetClusterMapRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetClusterMapResponse struct {
	Memlist []*github_com_chanyoung_nil_pkg_swimpb.Member `protobuf:"bytes,1,rep,name=memlist" json:"memlist,omitempty"`
}

func (m *GetClusterMapResponse) Reset()                    { *m = GetClusterMapResponse{} }
func (m *GetClusterMapResponse) String() string            { return proto.CompactTextString(m) }
func (*GetClusterMapResponse) ProtoMessage()               {}
func (*GetClusterMapResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetClusterMapResponse) GetMemlist() []*github_com_chanyoung_nil_pkg_swimpb.Member {
	if m != nil {
		return m.Memlist
	}
	return nil
}

type AddUserRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AddUserRequest) Reset()                    { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()               {}
func (*AddUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddUserResponse struct {
	AccessKey string `protobuf:"bytes,1,opt,name=accessKey" json:"accessKey,omitempty"`
	SecretKey string `protobuf:"bytes,2,opt,name=secretKey" json:"secretKey,omitempty"`
}

func (m *AddUserResponse) Reset()                    { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string            { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()               {}
func (*AddUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddUserResponse) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *AddUserResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GetClusterMapRequest)(nil), "github.com.chanyoung.nil.pkg.mds.mdspb.GetClusterMapRequest")
	proto.RegisterType((*GetClusterMapResponse)(nil), "github.com.chanyoung.nil.pkg.mds.mdspb.GetClusterMapResponse")
	proto.RegisterType((*AddUserRequest)(nil), "github.com.chanyoung.nil.pkg.mds.mdspb.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "github.com.chanyoung.nil.pkg.mds.mdspb.AddUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mds service

type MdsClient interface {
	GetClusterMap(ctx context.Context, in *GetClusterMapRequest, opts ...grpc.CallOption) (*GetClusterMapResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
}

type mdsClient struct {
	cc *grpc.ClientConn
}

func NewMdsClient(cc *grpc.ClientConn) MdsClient {
	return &mdsClient{cc}
}

func (c *mdsClient) GetClusterMap(ctx context.Context, in *GetClusterMapRequest, opts ...grpc.CallOption) (*GetClusterMapResponse, error) {
	out := new(GetClusterMapResponse)
	err := grpc.Invoke(ctx, "/github.com.chanyoung.nil.pkg.mds.mdspb.Mds/GetClusterMap", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdsClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := grpc.Invoke(ctx, "/github.com.chanyoung.nil.pkg.mds.mdspb.Mds/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mds service

type MdsServer interface {
	GetClusterMap(context.Context, *GetClusterMapRequest) (*GetClusterMapResponse, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
}

func RegisterMdsServer(s *grpc.Server, srv MdsServer) {
	s.RegisterService(&_Mds_serviceDesc, srv)
}

func _Mds_GetClusterMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdsServer).GetClusterMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.chanyoung.nil.pkg.mds.mdspb.Mds/GetClusterMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdsServer).GetClusterMap(ctx, req.(*GetClusterMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mds_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdsServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.chanyoung.nil.pkg.mds.mdspb.Mds/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdsServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.chanyoung.nil.pkg.mds.mdspb.Mds",
	HandlerType: (*MdsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterMap",
			Handler:    _Mds_GetClusterMap_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Mds_AddUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/mds/mdspb/mds.proto",
}

func init() { proto.RegisterFile("pkg/mds/mdspb/mds.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xad, 0x5a, 0x3a, 0xa2, 0xc2, 0xe2, 0x47, 0x29, 0x1e, 0x4a, 0x10, 0x29, 0x08, 0x1b,
	0x68, 0x41, 0x2f, 0x7a, 0x50, 0x11, 0x0f, 0x92, 0x4b, 0xc1, 0x8b, 0x07, 0x21, 0x1f, 0x43, 0x1a,
	0x9a, 0xdd, 0xac, 0x99, 0x0d, 0x52, 0xf0, 0x37, 0x78, 0xf2, 0x07, 0xcb, 0x6e, 0xd2, 0x94, 0x8a,
	0x48, 0xf5, 0x90, 0xc9, 0x32, 0xef, 0xbd, 0x79, 0x3b, 0x8f, 0x85, 0x63, 0x35, 0x4b, 0x3c, 0x11,
	0x93, 0xf9, 0x54, 0x68, 0x2a, 0x57, 0x45, 0xae, 0x73, 0x76, 0x96, 0xa4, 0x7a, 0x5a, 0x86, 0x3c,
	0xca, 0x05, 0x8f, 0xa6, 0x81, 0x9c, 0xe7, 0xa5, 0x4c, 0xb8, 0x4c, 0x33, 0xae, 0x66, 0x09, 0x37,
	0x3c, 0xab, 0xe8, 0x8f, 0x97, 0x3c, 0xaf, 0xe1, 0x79, 0x32, 0xcd, 0x3c, 0x33, 0x99, 0xde, 0x52,
	0x61, 0x8b, 0x0a, 0xed, 0xaf, 0x1a, 0xee, 0x1e, 0xc1, 0xc1, 0x03, 0xea, 0xbb, 0xac, 0x24, 0x8d,
	0x85, 0x1f, 0xa8, 0x09, 0xbe, 0x96, 0x48, 0xda, 0x7d, 0x81, 0xc3, 0x6f, 0x7d, 0x52, 0xb9, 0x24,
	0x64, 0xf7, 0xd0, 0x11, 0x28, 0xb2, 0x94, 0x74, 0xcf, 0x19, 0xb4, 0x87, 0x3b, 0xa3, 0x73, 0xfe,
	0xeb, 0xfd, 0x2a, 0x4b, 0xee, 0xa3, 0x08, 0xb1, 0x98, 0x2c, 0xb4, 0xee, 0x29, 0xec, 0xdd, 0xc4,
	0xf1, 0x13, 0x61, 0x51, 0x3b, 0x32, 0x06, 0x9b, 0x32, 0x10, 0xd8, 0x73, 0x06, 0xce, 0xb0, 0x3b,
	0xb1, 0x67, 0xd7, 0x87, 0xfd, 0x86, 0x55, 0xfb, 0x9f, 0x40, 0x37, 0x88, 0x22, 0x24, 0x7a, 0xc4,
	0x79, 0xcd, 0x5d, 0x36, 0x0c, 0x4a, 0x18, 0x15, 0xa8, 0x0d, 0xda, 0xaa, 0xd0, 0xa6, 0x31, 0xfa,
	0x6c, 0x41, 0xdb, 0x8f, 0x89, 0x7d, 0x38, 0xb0, 0xbb, 0xb2, 0x1d, 0xbb, 0xe2, 0xeb, 0x85, 0xcc,
	0x7f, 0x0a, 0xab, 0x7f, 0xfd, 0x4f, 0x75, 0xb5, 0x92, 0xbb, 0xc1, 0xde, 0xa1, 0x53, 0xef, 0xc9,
	0x2e, 0xd6, 0x9d, 0xb5, 0x1a, 0x5f, 0xff, 0xf2, 0xcf, 0xba, 0x85, 0xfb, 0x6d, 0xe7, 0x79, 0xcb,
	0x42, 0xe1, 0xb6, 0x7d, 0x13, 0xe3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x14, 0xd6, 0x5c,
	0x8b, 0x02, 0x00, 0x00,
}
