// Code generated by protoc-gen-go.
// source: pkg/mds/mdspb/mds.proto
// DO NOT EDIT!

/*
Package mdspb is a generated protocol buffer package.

It is generated from these files:
	pkg/mds/mdspb/mds.proto

It has these top-level messages:
*/
package mdspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mds service

type MdsClient interface {
}

type mdsClient struct {
	cc *grpc.ClientConn
}

func NewMdsClient(cc *grpc.ClientConn) MdsClient {
	return &mdsClient{cc}
}

// Server API for Mds service

type MdsServer interface {
}

func RegisterMdsServer(s *grpc.Server, srv MdsServer) {
	s.RegisterService(&_Mds_serviceDesc, srv)
}

var _Mds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.chanyoung.nil.pkg.mds.mdspb.Mds",
	HandlerType: (*MdsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/mds/mdspb/mds.proto",
}

func init() { proto.RegisterFile("pkg/mds/mdspb/mds.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xc8, 0x4e, 0xd7,
	0xcf, 0x4d, 0x29, 0x06, 0xe1, 0x82, 0x24, 0x10, 0xa9, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0xa4,
	0x96, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x97, 0x9c, 0x91, 0x98, 0x57,
	0x99, 0x5f, 0x9a, 0x97, 0xae, 0x97, 0x97, 0x99, 0xa3, 0x57, 0x90, 0x9d, 0xae, 0x07, 0x52, 0x07,
	0xd6, 0x61, 0xc4, 0xca, 0xc5, 0xec, 0x9b, 0x52, 0xec, 0xc4, 0x1e, 0xc5, 0x0a, 0xe6, 0x27, 0xb1,
	0x81, 0xb5, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xd8, 0x0b, 0x60, 0x59, 0x00, 0x00,
	0x00,
}
